twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig', 'site/app/_component/form/custom_types.html.twig']
    globals:
        etrans: '@App\Service\EntityTranslator'
        imageAssets: '%img_assets_directory%'
        assetsHashManager: '@App\Service\AssetsVersioning'
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
