twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        etrans: '@App\Service\EntityTranslator'
        imageAssets: '%img_assets_directory%'

when@test:
    twig:
        strict_variables: true
