#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: _guitar_list